### ISSUE TITLE
type is not resolved

### ISSUE THREAD

**Issue by usenetj23** [David-PLC/CWC-Area-Chart#1]
When import to V18 shows error "The type is not resolved"

**Comment by David-PLC** [comment]
> When import to V18 shows error "The type is not resolved"

I've tested everything with Tia 18 and ony PC everything runs ok, can you please be more specific about this issue?

**Comment by usenetj23** [comment]
TIA v18 update 1.
1. download repo archive
2. create zip from folder {4703190B-4D05-4F16-B52C-B4E3B46092C2}
3. copy zip to %programfiles%\Siemens\Automation\Portal V18\Data\Hmi\CustomControls
4. open project
5. go to MyControls and refresh
![2023-05-17 13_25_49-WETECHY142](https://github.com/David-PLC/CWC-Area-Chart/assets/46694838/cdbd7afc-8dfb-4d19-929d-37a6a96ce82b)

As you can see on screenshot other controls working fine.

**Comment by David-PLC** [comment]
You was right!
I've found the issue and updated the code now it should work with no problems.
You can download the code from the latest release!

Please test it and let me know if everything is ok so i can close the issue.
